// swift-tools-version: 5.9
import PackageDescription

// Generated by publish_to_public.sh. Edit the template there, not this file.
let package = Package(
    name: "swift-markdown-kit",
    platforms: [
        .iOS(.v17),
        // Mac Catalyst runs the same UIKit implementation, so macOS gets the
        // renderer that has been tested on iOS rather than a second one.
        .macCatalyst(.v17)
    ],
    products: [
        .library(
            name: "SwiftMarkdownKit",
            targets: ["SwiftMarkdownKit"]
        )
    ],
    targets: [
        // The framework is downloaded from this tag's release rather than
        // committed. A binary in git is permanent, and a package that carries
        // one makes every consumer clone every version ever published.
        //
        // The URL is immutable: a release asset cannot be replaced under a tag
        // that already exists, so this checksum stays correct for as long as
        // v0.0.10 does.
        .binaryTarget(
            name: "SwiftMarkdownKit",
            url: "https://github.com/cellgit/swift-markdown-kit/releases/download/v0.0.10/SwiftMarkdownKit-0.0.10.xcframework.zip",
            checksum: "25da3f640e4d66c80729e2aa48b96aab952690a0f93f5fdec8502942de1ad9f3"
        )
    ]
)
