// swift-tools-version: 5.9
import PackageDescription

// Generated by publish_to_public.sh. Edit the template there, not this file.
let package = Package(
    name: "swift-markdown-kit",
    platforms: [
        .iOS(.v17)
    ],
    products: [
        .library(
            name: "SwiftMarkdownKit",
            targets: ["SwiftMarkdownKit"]
        )
    ],
    targets: [
        // The framework is downloaded from this tag's release rather than
        // committed. A binary in git is permanent, and a package that carries
        // one makes every consumer clone every version ever published.
        //
        // The URL is immutable: a release asset cannot be replaced under a tag
        // that already exists, so this checksum stays correct for as long as
        // v0.0.3 does.
        .binaryTarget(
            name: "SwiftMarkdownKit",
            url: "https://github.com/cellgit/swift-markdown-kit/releases/download/v0.0.3/SwiftMarkdownKit-0.0.3.xcframework.zip",
            checksum: "24e03c7f0eabaff4e6941e275857a8660aeac36591b1546426725759478be090"
        )
    ]
)
